apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: resolver-listener
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: resolver-trigger 
      bindings:
      - ref: resolver-binding
      template:
        ref: resolver-template
        
# This declares that when an event is detected, it will run the TriggerBinding and the TriggerTemplate.

